version: "3.9"

services:
  app:
    container_name: fesensi-community
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    restart: unless-stopped
    env_file:
      - .env  # This will be copied by your webhook
    networks:
      - root_default
    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.fesensiCommunity.rule=Host(`community.fesensi.com`)"
      - "traefik.http.routers.fesensiCommunity.entrypoints=websecure"
      - "traefik.http.routers.fesensiCommunity.tls=true"
      - "traefik.http.routers.fesensiCommunity.tls.certresolver=mytlschallenge"

      # Service
      - "traefik.http.services.fesensiCommunity.loadbalancer.server.port=3000"

networks:
  root_default:
    external: true